### ISSUE TITLE
Fee not displayed in transaction info

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#100]
When I request transactions using `txs` or `gettx`, even when using `-y` or `-j`, I cannot see the transaction fee.

**Comment by plaprade** [comment]
Fees can only be computed/known for your own outgoing transactions as you need to know all the inputs values and all the output values of a transaction to compute the fee. We could display fees on outgoing transactions but incoming transactions won't have it displayed.

**Comment by xenog** [comment]
They only make sense really for outgoing transactions.

**Comment by plaprade** [comment]
Not necessarily. Knowing the fee on an incoming transaction might be useful in knowing if and when it will confirm.
