### ISSUE TITLE
PersistMarshalError while resyncing faucet wallet

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#109]
```
[Error] A database error occured: PersistMarshalError "field keyRing: int64 Expected Integer, received: PersistNull" @(haskoin-wallet-0.2.0:Network.Haskoin.Wallet.Server.Handler ./Network/Haskoin/Wallet/Server/Handler.hs:92:15)
```

**Comment by plaprade** [comment]
The error is referring to the keyRing field in the KeyRingAccount table. It is a foreign pointer to the ID of the KeyRing table. Can you describe how to reproduce the issue?

**Comment by xenog** [comment]
I rescanned the blockchain for a particular keyring used in the faucet. The scan was done from scratch. There was no previous database in that system. I will send the mnemonic to you by encrypted email.

**Comment by plaprade** [comment]
It seems the problem happens with SQLite but not MySQL. Will look further into it.

**Comment by xenog** [comment]
Solved in newest code.
