### ISSUE TITLE
cannot install head

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#110]
I would be interested in using, and maybe doing some development on haskoin / haskoin-wallet.

But I can't install it.

Can someone give reproducible instructions on how to install HEAD, or better still a known good dockerfile?

**Comment by xenog** [comment]
Recently we upgraded this package to use [Stack](https://github.com/commercialhaskell/stack/wiki/Downloads). It should be a lot easier than it used to be when we used the `cabal-install` tool. Have you followed the instructions in the `README.md` file at the root of the repository? These instructions should get you the same build plan, and we have tested them in Ubuntu 14.04 and 15.04 so far, so it should work also for Ubuntu 14.10 and most Linux distributions, provided you get the dependencies first.

If you have not tried to install using Stack following the instructions in the `README.md` file, please try that first and tell us your experience. If on the other hand you have done this already, and experiencing problems, would you please provide more information about the problems you have experienced?

Soon we will merge some non-trivial changes into this package that should break backwards compatibility with the current version. If you install now, and then you decide to install the latest version a few days into the future, you may have to delete your databases and rescan your wallet. Make sure to save your mnemonic. We can provide assistance should you need it. Good luck.

**Comment by tphyahoo** [comment]
this is my first time using stack, and I figured I'd try it out on macos.  So far no love.  

[thomashartman@papaya ~/installs/haskoin-wallet]$ time stack install
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      monad-control: needed (>=1.0 && <1.0), latest is 1.0.0.4, but 1.0.0.4 found
    needed for package: haskoin-wallet-0.2.0

real	0m2.602s
user	0m2.220s
sys	0m1.528s
[thomashartman@papaya ~/installs/haskoin-wallet]$ stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911

I did not perform this step from the README:

"Get pkg-config, LevelDB, Snappy, zlib and ØMQ"

but judging by the error above the snag I hit is unrelated.

recommendations?  Happy to try this on any os / version of stack if known to work.

**Comment by plaprade** [comment]
Hi tphyahoo, can you check the dependency version of monad-control in the haskoin-wallet.cabal file that you are installing? That dependency should be set as such:

`monad-control >= 1.0 && < 1.1`

which should be the value in the head of the master branch. I'm asking to check this specifically because we bumped the version of monad-control from 1.0 to 1.1 to support stack recently, and maybe you still have the old dependencies somehow? Let me know.

**Comment by tphyahoo** [comment]
my bad, I wasn't on head.

It buillt.

**Comment by plaprade** [comment]
Great, I'm glad it worked out. Current master head has some performance issues when you have large numbers of keys/transactions in your wallet. We are soon going to merge in the following branch which will fix those issues: #108 

Additionally, xenog is preparing a Dockerfile which he will share with us soon.
