### ISSUE TITLE
config file setting for bitcoin-full-nodes is ignored 

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#111]
first of all, is it possible to point hw at an external server?  I understand the security implications and why this might be a bad idea, I am just playing for now.

I tweaked config file for bitcoin nodes to nonsense settings to see at least this was being processed by hw, but it looks like actually it's not being processed.

How do you control the bitcoin node to connect to?

this should connect to notaserver.com:19333 (nonstandard server  with nonstandard port) but it looks like we still get default settings, no override.

	[thomashartman@papaya ~/installs/haskoin-wallet]$ hw --testnet start --config=./config/config.yml 
	[Info] [Blockchain] Running a full block locator. This can take some time. @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:104:19)
	.........
	[Warn] [PeerManager] Peer 3 closed ( 127.0.0.1:18333 ). Rescheduling pending jobs in the peer queue. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:242:7)
	[Info] [PeerManager] Reconnecting to remote host 127.0.0.1:18333 in 4 seconds. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:319:11)

tweaked settings, but no effect:

	[thomashartman@papaya ~/installs/haskoin-wallet]$ git diff ./config/config.yml 
	diff --git a/config/config.yml b/config/config.yml
	index e64d346..15970c0 100644
	--- a/config/config.yml
	+++ b/config/config.yml
	@@ -23,11 +23,11 @@ database:
	         port:     "_env:MYSQL_PORT:5432"
	 
	 ### List of trusted bitcoin full-nodes to connect to.
	+ bitcoin-full-nodes: 
	+   - host: "test.notaserver.com"
	+     port: 19333
	 # bitcoin-full-nodes: 
	-#   - host: "bitcoin.example.org"
	-#     port: 8333
	-bitcoin-full-nodes: 
	-  - host: "_env:BITCOIN_FULL_NODE:127.0.0.1"
	+#  - host: "_env:54.210.107.2:18333"
	 
	 # Log file name. Either absolute path or relative to work-dir/network
	 log-file: "_env:LOG_FILE:hw.log"

**Comment by plaprade** [comment]
Thanks for pointing this out. There may be a bug with resolving the path of the configuration file. I will look into it. However, you should be able to specify custom configuration settings by placing the configuration file in `~/.hw/config.yml`. Let me know if that works for you. If it doesn't, can you send me your configuration file again? There seems to have been some display issues with your first comment.

**Comment by tphyahoo** [comment]
when I place the config in ~/.hw/config.yml it works.

that leaves the problem with

  -g FILE        --config=FILE            Configuration file (default: config.yml)

I was able to solve this by specifying full path

~ is not a problem for specifying a file path under home. only  the following paths cause confusion:

hw --config=config/config.yml start  # without dot
hw --config=./config/config.yml start # with dot

a quick fix that would make things somewhat clearer would be

  -g FILE        --config=FILE            Configuration file (default: config.yml) # make this ~/.hw/config.yml

since the full path can be specified with --config flag.

whether it's worth fixing the confusion with current working dir, I don't know.

**Comment by tphyahoo** [comment]
another wrinkle in handling ~ for homedir: 

[thomashartman@papaya ~/installs/haskoin-wallet]$ hw --config ~/.hw/config.yml start # works without the =
	[Info] [Blockchain] Running a full block locator. This can take some time. @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:104:19)
	[Warn] [Blockchain] Trying to load an empty bloom filter @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:537:11)
	[Info] [Blockchain] Rescanning merkle blocks from timestamp 1436475137 @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:493:15)
	[Warn] [PeerManager] Peer 2 closed ( example.notaserver.com:18333:8333 ). Rescheduling pending jobs in the peer queue. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:242:7)
	[Info] [PeerManager] Reconnecting to remote host example.notaserver.com:18333:8333 in 2 seconds. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:319:11)
	^C
	[thomashartman@papaya ~/installs/haskoin-wallet]$ hw --config ~/.hw/config.yml start # does not work without the =
	[Info] [Blockchain] Running a full block locator. This can take some time. @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:104:19)
	[Warn] [Blockchain] Trying to load an empty bloom filter @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:537:11)
	[Info] [Blockchain] Rescanning merkle blocks from timestamp 1436475148 @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:493:15)
	[Warn] [PeerManager] Peer 2 closed ( example.notaserver.com:18333:8333 ). Rescheduling pending jobs in the peer queue. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:242:7)
	[Info] [PeerManager] Reconnecting to remote host example.notaserver.com:18333:8333 in 2 seconds. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:319:11)

**Comment by tphyahoo** [comment]
. has different behavior from `pwd` on mac shell

	[thomashartman@papaya ~/installs/haskoin-wallet]$ hw --config `pwd`/config/config.yml  start
	[Info] [Blockchain] Running a full block locator. This can take some time. @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:104:19)
	[Warn] [Blockchain] Trying to load an empty bloom filter @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:537:11)
	[Info] [Blockchain] Rescanning merkle blocks from timestamp 1436475977 @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:493:15)
	[Warn] [PeerManager] Peer 2 closed ( example.notaserver.com:18333:8333 ). Rescheduling pending jobs in the peer queue. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:242:7)
	[Info] [PeerManager] Reconnecting to remote host example.notaserver.com:18333:8333 in 2 seconds. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:319:11)
	^C
	[thomashartman@papaya ~/installs/haskoin-wallet]$ hw --config ./config/config.yml  start
	[Info] [Blockchain] Running a full block locator. This can take some time. @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:104:19)
	[Warn] [Blockchain] Trying to load an empty bloom filter @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:537:11)
	[Info] [Blockchain] Rescanning merkle blocks from timestamp 1436475983 @(haskoin-0.2.0:Network.Haskoin.Node.BlockChain ./Network/Haskoin/Node/BlockChain.hs:493:15)
	[Warn] [PeerManager] Peer 2 closed ( 127.0.0.1:8333 ). Rescheduling pending jobs in the peer queue. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:242:7)
	[Info] [PeerManager] Reconnecting to remote host 127.0.0.1:8333 in 2 seconds. @(haskoin-0.2.0:Network.Haskoin.Node.PeerManager ./Network/Haskoin/Node/PeerManager.hs:319:11)

**Comment by tphyahoo** [comment]
I guess we should probably close this bug and re-report to the relevant file path / config arg handling library.

unless hw rolled its own solution for this.

**Comment by plaprade** [comment]
Thanks for all this information. We can keep this bug report open for now. I wanted to refactor the configuration anyway as the current solution feels over-engineered (you can specify the configuration file and working directly at compile time and/or runtime which introduces complexity). I'll simplify all of that and at the same time drop the dependencies on Yesod (Yesod is only used for configuration stuff in haskoin).

**Comment by tphyahoo** [comment]
off topic, but my next step is to actually connect to a bitcoin node.

is there any cheat for this other than running satoshi locally and downloading the blockchain?

I was looking for something to connect to on
https://en.bitcoin.it/wiki/Fallback_Nodes and bitnodes.io, but first ten addresses I checked were unreachable.

are there public servers running, that support what hw needs? 

we're just downloading blocks here right? nothing that uses the json/rpc interface for satoshi client?

**Comment by plaprade** [comment]
hw only requires a bitcoin full node (so any of the bitcoin core nodes will do). It doesn't use any of the json/rpc commands. It is basically an SPV client similar to bitcoinj. It currently fetches and validates block headers, then downloads and imports merkle blocks. We have a full node running on faucet.haskoin.com if you want to use it. Otherwise, any other full node will do.

To connect to a different node than localhost by default, you simply need to change the `bitcoin-full-nodes` configuration value in config.yml.

**Comment by plaprade** [comment]
However, I'll add for anyone who may be reading that it is currently only recommended to run hw behind a trusted full node.

**Comment by xenog** [comment]
Paths with the `~` sign to refer to `HOME` are expanded by the shell only under some circumstances. One of the cases where the shell will not expand this is when there is a preceding character such as the equal sign. You may use `$HOME` instead of `~` in those circumstances.

About the dot character to refer to the current directory, that one does not get expanded by the shell. `hw` will use its working directory instead of the one you are calling it from. By default this is is `.hw` in `HOME`.

**Comment by tphyahoo** [comment]
I tried haskoin faucet and I'm at 256 timeout in the exponential backoff.

I guess my next move is to see if I can find another server, or provision my own.

If you think haskoin faucet should be serving blocks let me know and I'll try again and figure out what I was doing wrong.

**Comment by tphyahoo** [comment]
found a node!

I went down the list at https://getaddr.bitnodes.io/nodes/  , checked reachability using the reachability tool in previous message, and when one checked out set the config file to that address.

now downloading blocks.

**Comment by tphyahoo** [comment]
As an experience report, my ad hoc node that I pulled from on from above list lasted about five minutes and then went dark.

I guess when you use the satoshi client or similar software, once it makes the first connection it bootstraps a list of more nodes that are continually refreshed, to keep the blocks coming.  And haskoin-wallet currently doesn't do that.  And that is why it is recommended to run satoshi locally, or at any rate somewhere you control.

Mostly for fun, I am experimenting with scraping bitnodes for a longer list and seeing if I get farther.

 curl -sH "Accept: application/json; indent=4" https://getaddr.bitnodes.io/api/v1/nodes/leaderboard/?limit=100 | jq '.results | map (.node)' | grep -vE '\[|\]' | tr , "\n" | tr '"' "\n" | tr : "\n" | grep '\.'

gets a hundred fresh nodes.  I guess I will be running satoshi locally soon.

It would be nice if haskoin-wallet behaved more like satoshi in this respect, bootstrapping up an eternally active list of nodes, but I guess that's not on the short list of priorities.

**Comment by xenog** [comment]
You can do this to your configuration file:
```yaml
bitcoin-full-nodes:
  - host: testnet-seed.alexykot.me
  - host: testnet-seed.bitcoin.petertodd.org
  - host: testnet-seed.bluematt.me
  - host: testnet-seed.bitcoin.schildbach.de
```
For prodnet:
```yaml
bitcoin-full-nodes:
  - host: seed.bitcoin.sipa.be
  - host: dnsseed.bluematt.me
  - host: dnsseed.bitcoin.dashjr.org
  - host: seed.bitcoinstats.com
  - host: bitseed.xf2.org
  - host: seed.bitcoin.jonasschnelli.ch
```

**Comment by tphyahoo** [comment]
thanks!
