### ISSUE TITLE
Rescan after pre-generating addresses does not find all transactions

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#119]
In the faucet wallet, that contains many transactions and addresses, I pre-generated all internal and external addresses up to date by using these commands on a new instance of `hw`:

```sh
fw newkeyring ...
fw newacc faucet
fw genaddrs faucet {internal_count} -i
fw genaddrs faucet {external_count}
fw rescan 0
```

*Note:* The previous instructions should not not make sense to anyone but @plaprade and myself, but it is made public in case the issue affects somebody else.

**Comment by plaprade** [comment]
Fixed in #120
