### ISSUE TITLE
non-metadata non-privkey holding, transaction caching server should provides unspent outputs to signing-capable hw client upon request

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#122]
per convo in #5

**Comment by tphyahoo** [comment]
Suggested implementation:

Add

hw sync

to server commands for hw client.

This should 

  -- communicate mpubkeys and gap limits for all accounts the hw client knows about
      (only mpubkeys should be communicated, not account names or other metadata)
  -- hw server handler should start fetching relevant transactions from bitcoin network, and watching them thereafter.  (mind the gap limit if it changed)
  -- client should pull transactions from server
  -- on completion, you hw client gets "sync complete" status message or moral equivalent

Per #5, this "sync" command is the ONLY command data channel with which hw client should be communicating with hw server over the provided zmq facility.

All other commands should be hw client <-> hw client.

**Comment by xenog** [comment]
I would like a longer explanation about the last two paragraphs, I’m lost here:

>Per #5, this "sync" command is the ONLY command data channel with which hw client should be communicating with hw server over the provided zmq facility.
>
> All other commands should be hw client <-> hw client.

**Comment by tphyahoo** [comment]
OK, I'm thinking something like...

let's call the hw server a WatchingWallet, and the client a SigningWallet, just to give them roughly accurate names.  Both wallets have databases, but the schemas are different.  The SigningWallet schema is roughly what we have now.  The WatchingWallet db just caches transactions for mpubkeys, as discussed on #5 

In 

https://github.com/haskoin/haskoin-wallet/blob/master/Network/Haskoin/Wallet/Server.hs

looks like 

                => WalletRequest -> Handler m (WalletResponse Value)
	dispatchRequest req = liftM ResponseValid $ case req of
	    GetKeyRingsR                     -> getKeyRingsR
	    GetKeyRingR r                    -> getKeyRingR r
	    PostKeyRingsR r                  -> postKeyRingsR r
	    GetAccountsR r                   -> getAccountsR r
	    PostAccountsR r na               -> postAccountsR r na
	    GetAccountR r n                  -> getAccountR r n
	    PostAccountKeysR r n ks          -> postAccountKeysR r n ks
	    PostAccountGapR r n g            -> postAccountGapR r n g
	    GetAddressesR r n t m o p        -> getAddressesR r n t m o p
	    GetAddressesUnusedR r n t        -> getAddressesUnusedR r n t
	    GetAddressR r n i t m o          -> getAddressR r n i t m o
	    PutAddressR r n i t l            -> putAddressR r n i t l
	    PostAddressesR r n i t           -> postAddressesR r n i t
	    GetTxsR r n p                    -> getTxsR r n p
	    GetAddrTxsR r n i t p            -> getAddrTxsR r n i t p
	    PostTxsR r n a                   -> postTxsR r n a
	    GetTxR r n h                     -> getTxR r n h
	    GetOfflineTxR r n h              -> getOfflineTxR r n h
	    PostOfflineTxR r n t cs          -> postOfflineTxR r n t cs
	    GetBalanceR r n mc o             -> getBalanceR r n mc o
	    PostNodeR na                     -> postNodeR na

should get made over, and radically whittled down

WalletRequest should be split into two types

WatchingWalletRequest and SigningWalletRequest

WatchingWalletRequest pretty much has only constructors
  PostAccountKeysR [(MpubKey,GapLimit)]
  GetTxR  [MpubKey] -- (maybe this should be a tuple including gap limit as well, tbd)
  BroadcastTx tx (this one is almost optional, since you could go raw transaction and broadcast to any node)

Pretty much every other command gets moved to constructor for SigingWalletRequest, since it is keyring aware and this is where most of the action happens.

The WatchingWallet listens on the zmq interface for the few operations it supports.

Should the SigningWallet continue to use the zmq facility for handling its operations?  Maybe, not sure about that one.  The alternative is we just do everything in program, and keep a database handle open.  That is, we lose all the sendZmq bits in

https://github.com/haskoin/haskoin-wallet/blob/master/Network/Haskoin/Wallet/Client/Commands.hs

and just call the relevant methods directly.

Or, we continue to use zmq and an optional daemon for the signing wallet, and let the signing wallet even handle remote zmq requests if we want to live dangerously.

**Comment by tphyahoo** [comment]
Side note: it may be necessary to lock down hw server machine, otherwise there is ddos potential from attacher just swamping the caching box with spam mpubkeys.

**Comment by tphyahoo** [comment]
> a facility to store encrypted account/address/etc. labels on the server, eventually.

I don't want any metadata on the mpubkey -> transactions caching server.

However, this got me thinking.

Maybe there could be three modes of operation for the hw system.

1 -- transaction caching, no metadata
2 -- metadata aware, no privkeys (or maybe only hot wallet privkeys)
3 -- metadata aware + final signing authority (privkeys present, or connected on a hardware wallet)

with "wallet temperature" descending from hot to cold.

With this paradigm, wallet 2 could conceivably be online, with an unsigned transaction queue, and wallet 3 could be air gapped, with the database copied over on a usb stick for review, signing, and uploading back to 2.  When 2 gets the signed transactions, it would broadcast to 3.

Or, wallet 3 could be internet connected, but in a secure environment, and with high valley keys on a hardware wallet. Again, unsigned transactions flow there for review, they get signed and then sent up.  

This gives hw users a lot of flexibility in how they set up their security policies.

I think with this setup, the code doesn't actually change that much, because there is the option for metadata aware wallets (with account names) to serve on zmq, as before.  If you don't want the metadata aware wallets to serve, just don't run hw start on that machine.

Like / don't like?

**Comment by xenog** [comment]
I’m afraid I did not understand. Would you care to explain the architecture?

I’ll take the opportunity to write what I have in mind on the subject:

- server that keeps maps of xpub → transactions, xpub → utxo
- encrypted metadata storage (probably in the same server above, for simplicity)
- client

The client being the only one capable of signing transactions. A default client should be available as an `hw` command that at first should do a few simple things:

### Creating wallet

```
$ hw new
Encryption Passphrase: <mnemonic sentence or passphrase>
Again: <passphrase>
Mnemonic ([Enter] to create a new wallet): [mnemonic sentence of existing wallet]
New wallet created, seed: <mnemonic sentence of new wallet>
```

### Creating normal account

```
$ hw newacc normal --label "Simple is Better"
Passphrase: <mnemonic sentence or passphrase>
New normal account created.
```

### Creating multisig account

```
$ hw newacc multisig --keys 3 --sigs 2 --date 2013-07-13 --gap 10 \
> --pregen-internal 1200 --pregen-external 100 --label "Fun with Flags" \
> [xpub, ...]
Passphrase: <mnemonic sentence or passphrase>
New multisig account created, missing 1 keys, provide this xpub to other participants:
xpub...
```

### Adding your own key to an existing multisig account

```
$ hw newacc multisig --existing xpub --path /1337h
Passphrase: <mnemonic sentence or passphrase>
Added your own key to an existing multisig account. No more keys needed.
Account parameters (retrieved from server):
Label: Fun with Flags
External address count: 100
Internal address count: 1200
Creation date: 2013-07-13
Unused Address Gap: 10
```

### Creating a multisig transaction with your signature

```
$ hw send --from "Fun with Flags" <address amount, ...>
Passphrase: <mnemonic sentence or passphrase>
Transaction created, missing 1 signatures.
Multisig transaction ID: deadbeef1337
```

### Signing a multisig transaction

```
$ hw sign deadbeef1337
Transaction recipients (retrieved from server):
Address1: amount
Address2: amount
Sign? <y/n>
Passphrase: <mnemonic sentence or passphrase>
Transaction complete. Sent to network.
Transaction ID: 4ea174a94ac7109...
```

**Comment by tphyahoo** [comment]
I believe this is confusingly titled, and the important ideas are subsumed by #128 and #129 and we could continue there.  

Most of the complication involves rendezvous-ing for multisig shared key scenarios.

Close?
