### ISSUE TITLE
support bip45 "Structure for Deterministic P2SH Multisignature Wallets"

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#125]
Bip45, from the copay team at bitpay, is a well thought out wallet structure for supporting bip32 with multisig.  

I think it would be a good idea to adopt this standard.

https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki

**Comment by xenog** [comment]
Hey @tphyahoo,

I started a discussion regarding BIP-45 in the Bitcoin Development mailing list:

http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011356.html

You should probably look at it.

**Comment by tphyahoo** [comment]
this is an interesting thread

https://github.com/bitpay/copay/issues/2866

"Suggestion: Make 1-of-1 wallet adhere to BIP44 as normal p2pkh addresses"

In the end they didn't do it but I think the reasoning is interesting (and I don't yet fully follow.)

Seems to me a pity that 

-- deriv path for 1 or 1 wallet is not degenerate case of bip45
-- also there seems to be no way of creating multiple bip45 accounts for different sets of cosigners, because the hierarchy is too inflexible to allow it. So it seems if you have multiple unaffiliated groups of cosigners, you would need a wallet seed for each group rather than just having one seed and leveraging the hierarchy.  (I think this is related to your comments on the bitcoin-dev thread.)

Maybe there is an opportunity here to come up with something better than bip45 for multisig.

Copay is the only bip45 wallet so interoperability isn't that much of an issue.  

(If we come up with a better alternative, and lobby it effectively, bitcore might just follow the lead.)

**Comment by tphyahoo** [comment]
Actually I think I was wrong about

" also there seems to be no way of creating multiple bip45 accounts for different sets of cosigners, "

You can just generate various xpubkey however you like (bip44 for example) and use different xpubkeys with different cosigning groups.

An actual issue is:

you can't create multiple accounts (eg with labels) for the same cosigning group

So for example say you are a bank (or "wallet buddy") that provides security service via cosign.  You only cosign transactions after real account holder verifies identity and that it is him not a hacker.

Well, now there is no way for your client to create multiple labeled accounts (all with subaddresses) reusing some structure under m/45

he's got to set up a new multisig account, from fresh xpubkey on both his and the bank's end, every time. 

if there was one more level of hierarchy, the client and the  bank/wallet buddy would be able to come up with new accounts, with human label, without having to have somewhere to rendezvous for the fresh xpubkey joining.

I think copay overcomes this by having bws (bitcore wallet service) as an easy rendezvous point.

But it would be even better not to need one.

**Comment by tphyahoo** [comment]
I wish there was something like bip44, but leaving off the last two levels of hierarchy.

bip44 is 

m / purpose' / coin_type' / account' / change / address_index

I want just 

m / purpose' / coin_type' / account' 

purpose would be something like "ad hoc account." (46 say if that's available)

then you would get your ad hoc account(s), and spin out your bip44 or bip45 accounts under that.

all your bip44 and bip45 wallets (and whatever else) would be recoverable with just the seed.

**Comment by tphyahoo** [comment]
I wish we had the following tweak to bip45.

Instead of 

m / purpose' / cosigner_index / change / address_index 

do 

m / purpose' / cosigner_index / LABELED ACCOUNT / change / address_index 

This allows to use labeled accounts  to logically group derived addresses, same as bip44

it seems that bips cannot change after finalization, so this would require filing a new purpose scheme.

the human label for LABELED ACCOUNT could then be mirrored to the m of n account, as sort of a view.  Cosigners could make an effort to keep their labels in sync, or they could be ac hoc about it, and the wallet could report all applicable labels it knows about for the m of n objects.

This allows us to attach human labels ONLY to mpub keys, as I lobbied for elsewhere.

I think this keeps things simple and would make it easier to make wallet metadata compatible across wallets.

As an added bonus, 1 of 1 account keys would yield the same structure as bip44, and one could lobby to drop both bip44 and bip45 and just use this.  

another idea: 

m / purpose' / m / n /  cosigner_index / LABELED ACCOUNT / change / address_index 

encodes the m/n figures in the path.  I am not sure if what this buys us justifies the additional complexity. 

Essentially what it buys us is not mixing same pub keys across different m/n structures.

I'm not sure about this last one.

But I like the idea of a wallet hierarchy that supports both bip44 and bip45 style accounts, and allows ad hoc labels for both.

**Comment by xenog** [comment]
Hey,

Look at [this post](http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011363.html).  It solves some of the privacy leakage issue by adding a hash to the derivation path.

I don’t like the idea in Copay of having to exchange a wallet private key through secure means.  I prefer if the wallet participants were to reach a shared secret through ECDH.  Bitcoin is based on public key cryptography after all.  The keys already exist.

There are incompatibilities between what we are discussing here, and the mechanism I have suggested in #124 for tracking accounts and metadata on the server.  On that other ticket I have been discussing how to store multisig account information where an xpub is not shared among more than one set of cosigners, in the same way that haskoin-wallet does now.  Here we are discussing how we can use something like BIP-45 where your xpub is the same for every multisig account in which you are a cosigner.

In the bitcoin-dev thread Matias Alejo Garcia says:

> Thanks for the explanation. OK, maybe that should be stated on BIP45, but it was never the idea that you reuse your xpub for different wallet, as I mention on the original reply. The only implementation of BIP45 I am aware of (Copay), use completely different xprivs for each wallet.

I presume he means that you setup a single cosigning arrangement with a specific set of cosigners in Copay, and that is it.  If you want to setup a new arrangement, you need to generate another seed.  It does not use the power of HD wallets to allow multiple accounts with different cosigners.  I will suggest that we abandon the pursuit of BIP-45 and focus on the existing haskoin-wallet model of different xpubs on every multisig account.

Greetings

**Comment by tphyahoo** [comment]
I tentatively agree that maybe hw should close this and shoot for something better than bip45, because of the privacy issues you have raised.

I think this is incorrect or worded confusingy:

"I don’t like the idea in Copay of having to exchange a wallet private key through secure means."

IIUC, with copay you exchange a shared wallet pub key, which is actually a tuple of xpubkeys from all the cosigners.  BTW Is there a word for this? How about "XPubKey Tuple" ?

Now, there are two, basically orthogonal, privacy issues with copay/bip45

-- 1) the secure channel rendezvous point knows all the Multisig XPubKey Tuples 
-- 2) even if the xpubkeys were not communicated via a possibly insecure rendezvous point, if xpubkeys are reused among different cohorts of cosigners, you leak info there as well to every cohort that knows your recycled xpubkey

You propose to solve issue 1 by switching to a zero knowledge rendezvous point, where the data is encrypted via a (non composite) xpubkey that is the product of diffy hellman of the composite xpubkeys.

BTW how about calling this "Diffie Hellman Merged XPubKey Tuple" ?

You propose to solve issue 2 by contructing a derivation path that is deterministic for every Multisig Composite XpubKey, but requires knowing ever xpubkey in the set (via cryptographic 1 way hash).

How about calling this 

BIP00NN "Hashed Path Structure for Deterministic P2SH Multisignature Wallets"

So far so good. 

Here's my feedback.  

Diffie Hellman, assuming it does the right thing, gets you a zero knowledge server, solving point 1.  I think the rendezvous mechanism could be tricky from a usability standpoint, and I think we should address this soon to get really convinced that it's usable.

But granted that, I'm sold on DH Merged XPubKey Tuples, for securing shared metadata.

As to point 2, your proposal on bitcoin-dev seems reasonable to me.  

However, I made an alternative proposal above "ad hoc account" that I believe solves the same problem in a simpler way.  Basically you have a "master wallet" what you treat as a "wallet key chain" and you spin out bip44 and bip45 (and whatever else) wallets as needed under that. Pro is, it is bip45 compatible.  Con is, it forces the wallet holder to enforce privacy hygiene by generating new pubkey for every Multisig XPubKey Tuple he wants to cosign in. However, good hygiene could be enforced by software at the wallet key chain level -- the user could get a warning if he tries to join a new Multisig XPubKey Tuple with a pubkey that is known to already be in use for a separate Multisig XPubKey Tuple.

I had a different complaint about bip45 than you did.  It seems to me that bip45 doesn't allow named accounts (with sub addresses) in the same way that bip44 does.  It's just one level, and then a bunch of addresses.  

So, I think this is a good recap and I will wait for your replies on the following points

-- How do you propose to handle rendezvous for constructing Diffie Hellman Merged XPubKey Tuple, so we can keep multisig accounts zero knowledge? (I am thinking usability here.)
-- What do you think of "master wallet" / "ad hoc account"
-- What do you think of, at least supporting bip45, via ad hoc account mechanism to solve reuse of xpubkey issue
-- What do you think of bip45-like but new hierarchy, with more flexibility for named accounts?

**Comment by tphyahoo** [comment]
As a final thought, I think if we can make single signer wallets (generally bip44 now) a degenerate case of multi signer wallets, that would be a good thing.

**Comment by xenog** [comment]
Yeah, that is the scheme we have so far.  Some accounts are single-sig and some are multi-sig, and they just share the same hierarchy.  Metadata completes the missing information like the list of keys and the number of required signatures.  I'll close.
