### ISSUE TITLE
support bip44   Multi-Account Hierarchy for Deterministic Wallets

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#127]
I think hw is already close to following bip44, but it doesn't use the purpose field and I am not sure about the other details.

Mainly this would be a win in terms of interoperability with other wallets.  Most are switching to bip44.

**Comment by xenog** [comment]
Yeah, I agree, we should do this change.

**Comment by xenog** [comment]
We can create this issue again in the new repository.
