### ISSUE TITLE
trezor-like hardware wallet support for privkey/seed management

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#131]
This is a stub task to break off "metadata encryption key" discussion in #124, into more manageable threads.

Responding to last comments by xenog:

"Although Trezor seems to be selling for about US$ 130 in some places"

https://www.ledgerwallet.com/products/3-ledger-hw-1

has almost same security model and is a lot cheaper at I think < $20 (but no screen).  There is also the bwallet knockoff of trezor from china.  If bitcoin is on the success path, eventually these things will be free in cereal boxes.  But it will take awhile.  But I like to plan for success. There are also trusted bits of hardware in phones with trezor-like properties, that will roll out soon if they haven't already.

I think there is agreement that it would be nice to support trezor-like hardware wallets, that can leak signatures on bad addresses if there was an address substitution attack, but will never leak privkeys.

**Comment by tphyahoo** [comment]
Xenog in #124 also objected 

"Forcing everyone to use a Trezor or similar device will harm the convenience side of things (no mobile), "

I'm pretty sure that's not true

https://www.youtube.com/results?search_query=android+ledger+nano

https://www.youtube.com/watch?v=8BUi9trE0e4

**Comment by tphyahoo** [comment]
Also I don't advocate forcing everyone to use a trezor-like.

I want to nudge in that direction, rather than encrypting via #133 because when there is money involved knowledge is better than faith, and we know #133 leaks privkeys in the event of security breach and a trezor-like doesn't.  

I think the additional security provided by a passphrase/hardware token that can still leak privkeys, is confusing and hard to judge, because you wind up thinking about the security of the machine as a system (viruses / trojans) rather than physical security, and this kind of thought process breeds paranoia and not wanting to use bitcoin.

However, I don't want to force my views on anyone, just educate on the pros and cons.

Seed phrase in a config file for low value wallets is fine.

**Comment by xenog** [comment]
Closing in this repository. We can continue this discussion in the new repository.
