### ISSUE TITLE
mepin-like 2-factor auth functionality for trusted upstream multisig cosigner 

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#132]
This is a stub task to break off "metadata encryption key" discussion in #124, into more manageable threads.

I'm not sure how the mepin works, or if it is similar to google auth / auth, or something different.

Just filing something here to disentangle and prioritize the threads.

**Comment by tphyahoo** [comment]
relevant snip from #124:

"One possible solution for this scenario by the way involves multisig and MePIN, which pops a notification on your smartphone showing the actual address and amount that the transaction goes to for signing on another system"

I would view a mepin like solution (and many variants) as something that would be built on top of basic hw functionality.  I call these "wallet buddies. The add-ons would involve both client and upstream server functionality.  

A wallet buddy could be like mepin, as you describe.

Or, it could be your family sysadmin, who is expected to have a secure machine, who will actually make a video skype call and confirm the hash of a transaction sig for high value transactions; when grandma wants to sell a lot of her bitcoin.

At any rate, this type of solution implies smooth multisig, and maybe #128 / zero knowledge metadata storage as well for cloud solutions.

So I think this would come later in the roadmap than #131 and #133.

Maybe there is an intermediate step for stub "wallet buddy"-like workflow, which could be adapted to either the mepin or the video-skype grandma scenario.

**Comment by tphyahoo** [comment]
I think the upstream cosigner is likely to want #131 security on their systems, where they have a lot more bitcoin to protect and the hardware cost isn't an issue. 

IMHO, #133 is not a good enough solution for trusted cosigners, who will be enforcing identity / velocity decisions in the wallet buddy scenario.  #133 might be good for some cases, but honestly I'm not sure which ones.  Why would you ever want to expose leaking all privkeys, when there is a straightforward not that expensive alternative? Assuming you're in the cosigner role I mean.

**Comment by tphyahoo** [comment]
As a side note, a trezor with disabled pin would make a very nice hot wallet protection device, in the mepin scenario.

https://doc.satoshilabs.com/trezor-user/advanced_settings.html

The oracle enforces identity and velocity rules, and if the hot wallet runs low requests more bitcoin from another source.  Maybe one where a human is in the loop and has to enter a pin.

**Comment by xenog** [comment]
Closing in this repository. We can create again in new repository if necessary.
