### ISSUE TITLE
passphrase / hardware token encryption for privkey/seed management

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#133]
This is a stub task to break off "metadata encryption key" discussion in #124, into more manageable threads.

This task encompasses storing seed/privkey encrypted only, and requiring second factor (either a passphrase or a hardware token) to decrypt the privkeys/seed.

Note that unlike the trezor-like solution in #131, this solution leaks privkeys in the event of a rooted machine, whereas the trezor-like solution only leaks signtures on substituted addresses in the worst case.

I view these "key management" tasks mostly through the lens of user education, and nudging users to make the right choices and compromises based on the value of what they are protecting.

**Comment by tphyahoo** [comment]
As is probably evident by now, from comments in #131 and #132, I don't like this feature as I think it 

-- provides trusting users with false sense of security
-- inflicts paranoid users down the rabbit hole security paranoia, thinking about trojans and viruses

and advocate instead, either non-privkey leaking hardware security of #131, or "wallet buddy" delegation of security in #132 (which in turn likely relies on #131 with cosigner), or just store the seed locally in plain text or enter it every time at the prompt, which is a little inconvenient but at least conditions the user to long random passwords.  (6 words for a low value bip39 seed isn't that bad).

We want to avoid security by obscurity, especially in the mind of the user.

**Comment by xenog** [comment]
Closing in this repository. We can create again in new repository if necessary.
