### ISSUE TITLE
pie in the sky: tamper resistant wallet data

### ISSUE THREAD

**Issue by tphyahoo** [haskoin/haskoin-wallet#134]
this branches off #129 

Thoughts.

I'm not sure if metadata is the right word.  Maybe it's just "accounting data"?

This leads to...

<pie in the sky mode>

It would be cool if the metadata (accounting data) was tamper resistant, by tying it to the blockchain somehow.  There are numerous schemes to do this... factom, and tradle (now collaborating -- http://blog.factom.org/post/113426992274/tradle-factom-announce-collaboration ) is one I follow, bitpay has chaindb, there was an alas failed kickstarter for gitchain, there is Storj/hashserv, and I think there are probably some others.  There's none that I am currently totally sold on.  

But I think there's something to the notion that the fundamental intuition behind bitcoin is that you are writing with a pen of indelible ink.  

At any rate... with tamper resistant metadata, now when we label a transaction, it becomes provably hard to relabel it if we want to fiddle the books.

</pie sky off>

**Comment by xenog** [comment]
Do you know of any possible distributed storage mechanism that can be used to completely remove the need for server-side-storage? Anything from `OP_RETURN` will do.

**Comment by sekharkumarroy** [comment]
OP_RETURN has limited storage capacity. All you can possibly store there is
a hash.
You may try IPFS(http://ipfs.io/) or StorJ(http://storj.io/)  both has
command line as well as API support.

**Comment by xenog** [comment]
Thanks @sekharkumarroy. I'm familiar with those. I wonder how reliable are they at this point. I have been reading the IPFS paper, and it seems to be well thought-out. I haven't read much about StorJ yet.

**Comment by tphyahoo** [comment]
I think eventually one or more solutions like ipfs or storj will emerge as a leader in terms of storing data reliably without a central point of failure, but at this point it's too early in the game.

Tamper resistance is a much more tractable feature.  We know how to do it economically -- embed a hash of merkle hashes of versions in the blockchain. It's just a matter of choosing an underlying system for the data, and then building up the mechanisms for finally writing the tamper seal to the blocchain.

There are a number of schemes rising up to do tamper resistance, and many to me have the taint of half baked wanna-be altcoin. Factom, storj, ipfs again come to mind -- these have stories for tamper resistance as well as data storage.  Others solutions are just immature and untested.  My favorite (just casual, no deep due diligence) is Tierion, a blatantly commercial (I think not-open-source) solution tha is seeing use and whose api was picked up by zapier, making integrations easy for excel and mba types.

Taking a step back for wider view, we have following problems to solve, which are somewhat linked
-- Database.
   This should use checkpoints + deltas, so tamper resistance feature below has concrete semantics for what can't be tampered. (Currently sqlite, which iiuc lacks deltas+checkpoints.)
-- the data should be zero knowledge, for any centralized pieces of the architecture
-- safety and durability of the data itself (backups)
-- tamper resistance. amounts to hashing + signing deltas in database above.

When you look at these requirements, you realize that the durability piece is the easy piece.

For durability, you can put it in tarsnap as I suggested in an another github issues thread, or s3, or just take responsibility for being admin on backup machine yourself.  Perhaps this should be out of scope of wallet hardware, and the objective would be to make it easy for user to choose their own backup solution, with friendly nudges toward the recommended pathways.

If you use tarsnap you get zero knowledge for free.

If you use a service like tierion, you get tamper resistance as long as the underlying data has sane checkpoints and deltas. I don't think sqlite has this, but I think postgres with logging or github with frequent commits, or various other means would do the trick.

So the question becomes, where do you go "roll your own" and where do you depend on pre existing software and (possibly proprietary) services.

I am thinking about acid-state instead of sqlite.

https://hackage.haskell.org/package/acid-state

Acid-state is a general purpose solution for serializing stateful haskell data.  
This could be enhanced to add general purpose functionality for hashing and signing the deltas, and perhaps even do the blockchain insertion piece.  
Sounds awesome, but a lot of work. But if accomplished, can be applied to "blockchainify" all sorts of other haskell apps that follow the model.

The less ambitious option is to switch to postgresql with logs, and checkpoint+hash+signing the logs.

I guess the intuition I am having here is that it would be good to sniff around haskell ecosystem for places where moderate amount of work would radically increase utility of haskell ecosystem for "blockchainifying" existing processes for low-cost enhancements to achieve blockchain based tamper resistance and auditability.

Bringing this full circle: haskoin-wallet should use logging database and has some metric of 
what it means to tamper the data in terms of what level of delta needs to be sealed.  Once that is solved, blockchain-enabling this to make it real world tamper proof is almost trivial.

**Comment by xenog** [comment]
I'll close in this repository. We could create this in the new repository if we want to continue this discussion.
