### ISSUE TITLE
Improve the handling of dust transactions

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#15]
Dust must be 5430, not 5000.

**Comment by plaprade** [comment]
The value has been fixed but I'll keep issue open to remind us to deal with dust in a better way.

**Comment by xenog** [comment]
Usually I would expect the coin selection algorithm to ignore dust. I can think of a few cases where the algorithm may fail to do this.

I believe that the amount considered dust may have been reduced in the latest bitcoind.
