### ISSUE TITLE
Use entities instead of names for the internal API

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#34]
Currently lots of functions in the internal wallet API (stuff under Network/Haskoin/Wallet) use names to search for things, sometimes forcing the application to do multiple queries for the same item during the course of a set of operations on the database. It is faster and more concise if we the Entity data type whenever possible, even if that exposes the database context a bit.

**Comment by plaprade** [comment]
Most of the internal database API now uses entities, except for some cases where a function is only meant to be called from outside the API. I think most instances of redundant fetches have been removed.
