### ISSUE TITLE
More information per address

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#59]
We need a way for the API to obtain address balance, a list of transactions affecting it, and possibly the length of this list separately.

**Comment by plaprade** [comment]
We now have the following information on addresses:
- In balance
- Out balance
- Offline in balance (in balance + in balance from offline transactions)
- Offline out balance (out balance + out balance from offline transactions)
- API function addrtxs returns all the transactions relevant to a given address. The satoshi values of those transactions are computed with respect to the given address (amount sent to the address or amount leaving the address).

Is this sufficient to close this feature request ?
